### ISSUE TITLE
Typos in the About section

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/weather-report#10]
![image](https://github.com/user-attachments/assets/769d44d6-9a28-45c2-829f-a249eb9b8acd)

wit -> with
analitics -> analytics

Also I'd probably use `for` instead of `about`.

**Comment by Czaki** [comment]
May you open PR?

**Comment by psobolewskiPhD** [comment]
No idea how to change that in a PR. it's the about, top right. I don't have permissions to directly edit either.

**Comment by psobolewskiPhD** [comment]
![image](https://github.com/user-attachments/assets/e422f8c0-bb21-4aba-a863-6fe8d3336f80)

**Comment by Czaki** [comment]
Ah. This about. Changed
